import json

cases = {"apn1": [{'Action': 'adapter_test_command', 'Parameter': '37,3,2,2,1,0,2,2,0,2,3,0,8,18'},
                  {'Action': 'wait', 'Parameter': '5'},
                  {'Action': 'check_network_pass', 'Parameter': 'ping v.nioint.com -c4'},
                  {'Action': 'adapter_test_command', 'Parameter': '37,2,1,1,8,18'},
                  {'Action': 'wait', 'Parameter': '5'},
                  {'Action': 'check_network_fail', 'Parameter': 'ping v.nioint.com -c4'}],
         "apn2": [{'Action': 'adapter_test_command', 'Parameter': '37,3,2,2,2,0'},
                  {'Action': 'wait', 'Parameter': '5'},
                  {'Action': 'check_network_pass', 'Parameter': 'ping www.baidu.com -c4'},
                  {'Action': 'adapter_test_command', 'Parameter': '37,2,2,1,8,18'},
                  {'Action': 'wait', 'Parameter': '5'},
                  {'Action': 'check_network_fail', 'Parameter': 'ping www.baidu.com -c4'}],
         "apn3": [{'Action': 'adapter_test_command', 'Parameter': '37,3,2,2,1,0,2,2,0,2,3,0,8,18'},
                  {'Action': 'wait', 'Parameter': '5'},
                  {'Action': 'check_network_pass', 'Parameter': 'ping www.baidu.com -I rmnet_data0 -c4'},
                  {'Action': 'adapter_test_command', 'Parameter': '37,2,3,1,8,18'},
                  {'Action': 'wait', 'Parameter': '5'},
                  {'Action': 'check_network_fail', 'Parameter': 'ping www.baidu.com -I rmnet_data0 -c4'}],
         "cfun": [{'Action': 'adapter_test_command', 'Parameter': '37,3,2,2,1,0,2,2,0,2,3,0,8,18'},
                  {'Action': 'wait', 'Parameter': '40'},
                  {'Action': 'check_network_pass', 'Parameter': 'ping www.baidu.com -c4'},
                  {'Action': 'send_command', 'Parameter': 'ql_cmd at at+cfun=4'},
                  {'Action': 'wait', 'Parameter': '10'},
                  {'Action': 'check_network_fail', 'Parameter': 'ping www.baidu.com -c4'},
                  {'Action': 'reboot', 'Parameter': '200'},
                  {'Action': 'wait', 'Parameter': '30'},
                  {'Action': 'check_network_pass', 'Parameter': 'ping www.baidu.com -c4'}],
         "flymode": [{'Action': 'adapter_test_command', 'Parameter': '37,3,2,2,1,0,2,2,0,2,3,0,8,18'},
                     {'Action': 'wait', 'Parameter': '30'},
                     {'Action': 'check_network_pass', 'Parameter': 'ping www.baidu.com -c4'},
                     {'Action': 'adapter_test_command', 'Parameter': '37,3,1,8,18'},
                     {'Action': 'wait', 'Parameter': '10'},
                     {'Action': 'check_network_fail', 'Parameter': 'ping www.baidu.com -c4'}],
         "hardkey": [{'Action': 'adapter_test_command', 'Parameter': '37,1,1'},
                     {'Action': 'wait', 'Parameter': '60'},
                     {'Action': 'check_network_pass', 'Parameter': 'ping www.baidu.com -c4'}],
         "softkey": [{'Action': 'adapter_test_command', 'Parameter': '37,1,0'},
                     {'Action': 'wait', 'Parameter': '60'},
                     {'Action': 'check_network_pass', 'Parameter': 'ping www.baidu.com -c4'}],
         "reboot": [{'Action': 'adapter_test_command', 'Parameter': '37,3,2,2,1,0,2,2,0,2,3,0,8,18'},
                    {'Action': 'wait', 'Parameter': '5'},
                    {'Action': 'check_network_pass', 'Parameter': 'ping www.baidu.com -c4'},
                    {'Action': 'reboot', 'Parameter': '200'},
                    {'Action': 'wait', 'Parameter': '30'},
                    {'Action': 'check_network_pass', 'Parameter': 'ping www.baidu.com -c4'}]
         }

with open('cases.json', 'w') as f:
    json.dump(cases, f, indent=4)
print(cases)
